package com.caidongdong.aestheticism.entity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table User.
 */
public class User {

    private Long id;
    private String User_Name;
    private String PassWord;
    private String Gender;
    private Integer Phone_Num;
    private String True_name;
    private String ID_Card;
    private String Create_Time;
    private String Update_Time;
    private String Last_Login_Time;
    private Boolean Enable;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, String User_Name, String PassWord, String Gender, Integer Phone_Num, String True_name, String ID_Card, String Create_Time, String Update_Time, String Last_Login_Time, Boolean Enable) {
        this.id = id;
        this.User_Name = User_Name;
        this.PassWord = PassWord;
        this.Gender = Gender;
        this.Phone_Num = Phone_Num;
        this.True_name = True_name;
        this.ID_Card = ID_Card;
        this.Create_Time = Create_Time;
        this.Update_Time = Update_Time;
        this.Last_Login_Time = Last_Login_Time;
        this.Enable = Enable;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUser_Name() {
        return User_Name;
    }

    public void setUser_Name(String User_Name) {
        this.User_Name = User_Name;
    }

    public String getPassWord() {
        return PassWord;
    }

    public void setPassWord(String PassWord) {
        this.PassWord = PassWord;
    }

    public String getGender() {
        return Gender;
    }

    public void setGender(String Gender) {
        this.Gender = Gender;
    }

    public Integer getPhone_Num() {
        return Phone_Num;
    }

    public void setPhone_Num(Integer Phone_Num) {
        this.Phone_Num = Phone_Num;
    }

    public String getTrue_name() {
        return True_name;
    }

    public void setTrue_name(String True_name) {
        this.True_name = True_name;
    }

    public String getID_Card() {
        return ID_Card;
    }

    public void setID_Card(String ID_Card) {
        this.ID_Card = ID_Card;
    }

    public String getCreate_Time() {
        return Create_Time;
    }

    public void setCreate_Time(String Create_Time) {
        this.Create_Time = Create_Time;
    }

    public String getUpdate_Time() {
        return Update_Time;
    }

    public void setUpdate_Time(String Update_Time) {
        this.Update_Time = Update_Time;
    }

    public String getLast_Login_Time() {
        return Last_Login_Time;
    }

    public void setLast_Login_Time(String Last_Login_Time) {
        this.Last_Login_Time = Last_Login_Time;
    }

    public Boolean getEnable() {
        return Enable;
    }

    public void setEnable(Boolean Enable) {
        this.Enable = Enable;
    }

}
